package com.neupanesushant.kastha.appcore

object RouteConfig {
    const val MAIN_ACTIVITY = "MAIN_ACTIVITY"
    const val AUTHENTICATION_ACTIVITY = "AUTHENTICATION_ACTIVITY"
    const val LOGIN_FRAGMENT = "LOGIN_FRAGMENT"
    const val OTP_FRAGMENT = "OTP_FRAGMENT"

    const val ONBOARDING_FRAGMENT = "ONBOARDING_FRAGMENT"
    const val FP_RESET_FRAGMENT = "FP_RESET_FRAGMENT"
    const val SIGN_UP_FRAGMENT = "SIGN_UP_FRAGMENT"
    const val FP_EMAIL_VERFICATION_FRAGMENT = "FP_EMAIL_VERIFICATION_FRAGMENT"
}