package com.neupanesushant.kastha.appcore

object RouteConfig {
    const val MAIN_ACTIVITY = "MAIN_ACTIVITY"
    const val AUTHENTICATION_ACTIVITY = "AUTHENTICATION_ACTIVITY"

    // Authentication
    const val LOGIN_FRAGMENT = "LOGIN_FRAGMENT"
    const val OTP_FRAGMENT = "OTP_FRAGMENT"
    const val ONBOARDING_FRAGMENT = "ONBOARDING_FRAGMENT"
    const val FP_RESET_FRAGMENT = "FP_RESET_FRAGMENT"
    const val SIGN_UP_FRAGMENT = "SIGN_UP_FRAGMENT"
    const val FP_EMAIL_VERFICATION_FRAGMENT = "FP_EMAIL_VERIFICATION_FRAGMENT"

    // Main
    const val HOME_FRAGMENT = "HOME_FRAGMENT"
    const val PROFILE_FRAGMENT = "PROFILE_FRAGMENT"
    const val CART_FRAGMENT = "CART_FRAGMENT"
    const val CATEGORIES_FRAGMENT = "CATEGORIES_FRAGMENT"
    const val CATEGORIES_VIEW_PAGER_FRAGMENT = "CATEGORIES_VIEW_PAGER_FRAGMENT"
    const val FAVOURITES_FRAGMENT = "FAVOURITES_FRAGMENT"
}